Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Max: 55

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Style/AsciiComments:
  Enabled: false
