Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 70

Metrics/PerceivedComplexity:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 11

Style/ClassVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false
