Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Style/AsciiComments:
  Enabled: false
